### ISSUE TITLE
Intro-Bildschirme (Thomas)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#1]
- [x] gibst du an, welche (Komma)
- [x] Gib bitte zudem... (Grossbuchstabe)
- [x] gibt bitte an, wieviel (Komma)
- [x] gespült (ohne h)
- [x] gibt bitte an, warum (Komma)
- [x] finde die formulierung komisch, würde schreiben: Zunächst den Hauptgrund und dann allenfalls noch weitere Gründe
- [x] „Fünftens weitere Gründe“ warum kommt das noch einmal?

**Comment by lucasetti** [comment]
Anpassung gemacht!
file: intro_01
Übersetzungen folgen!
