### ISSUE TITLE
Überall Höflichkeitsform mit Du verwenden (Rita)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#11]
- dein = Deine (Höflichkeitsform verwenden)

**Comment by lucasetti** [comment]
habe mal irgendwo gelesen das Grossschreibung nur noch bei der Sie-Form zum tragen kommt.
Aber ist nicht meine Steckenpferd und können wir gerne ändern!

**Comment by ssr3** [comment]
Gemäss der neuen deutschen Rechtschreibung kann man "du" oder "Du" schreiben, allerdings empfiehlt die Dudenredaktion die gross geschriebene Variante "Du".
(Und ich persönlich schreibe auch jeweils "Du", auch in der privaten Korrespondenz. Ich finde das irgendwie respektvoller. Und gerade, wenn wir von den Leuten etwas wollen, kann etwas Höflichkeit nicht schaden.
Das kleine "du" hingegen passt in den Kontext "wir sind alle jung und cool", aber das ist ja nicht unsere alleinige Zielgruppe.
Soweit mein Plädoyer für "Du". Aber wie gesagt, auch das kleine "du" wäre korrekt.")

**Comment by lucasetti** [comment]
Ok, danke für die Ausführungen und finde ich gut! Werde ich anpassen!
Am 13.07.2016 11:16 vorm. schrieb "ssr3" notifications@github.com:

**Comment by thomasbrunnerbfh** [comment]
passt für mich (obwohl ich ein konsequenter kleinschreiber bin ;-))
