### ISSUE TITLE
Menge (Rita)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#17]
- Seite zu „Menge“ (Schritt 2, oder?): verschiebt sich beim Wischen (sowohl wenn man vom Schritt 1 kommt als auch wenn man zu Schritt 3 will) nur ein wenig nach links, so dass die Zeilentitel nur halb lesbar sind. Man bleibt quasi stecken zwischen den beiden Schritten.

**Comment by lucasetti** [comment]
webapp issue! Wenn behebbar nice, aber sicher nicht erste prio!
