### ISSUE TITLE
Lebensmittelkategoriesuche (Thomas)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#2]
wenn ich „ba“ für banane eingebe, kommt rhabarber und andere dinge, wo das „ba“ in der mitte des wortes vorkommt. so sucht kein mensch! kann man das nicht so machen, dass nur wörter kommen, mit „ba“ am anfang?

**Comment by MichaelRoethlin** [comment]
Rita dazu: Wenn ich z.B. „Z“ eingebe und suche, kommen ganz viele Begriffe ohne „Z“ drin.

**Comment by lucasetti** [comment]
Diese Suche  "in allen Bereichen der Worte" (sorry weiss Fachterm gerade nicht mehr...) wurde mal so festgelegt, dass man z.B. für die Eingabe "Käse" sowohl Hartkäse als auch Frischkäse oder ähnlich angezeigt erhält.
Ich finde das durchaus sinnvoll aber wenn nicht gewünscht, kann das gerne weggelassen werden.
bei der Eingabe "Ban" kommen übrigens nur noch die Bananen ;-) :-)

**Comment by ssr3** [comment]
Hallo zusammen,
mit dem Browser auf dem Handy:
wenn ich "zitrone" eingebe, kommt als erstes "Kefen", dann "Linsen, Fischstäbchen,...". Zitrone ist nirgends ersichtlich.

**Comment by MichaelRoethlin** [comment]
Achtung: evtl. muss der Browser-Cache geleert werden. In meinem Browser (Chrome auf Mac, Cache frisch geleert) sieht alles i.O. aus.
![zitronenproblem](https://cloud.githubusercontent.com/assets/4992205/16800126/fa3c5680-48f3-11e6-9db2-d298ae631145.png)

**Comment by ssr3** [comment]
Hallo Michael

Hmm, wie löscht man auf dem Handy (iPhone 4) den Cache des Browsers? (habe Cookies, Daten, Verlauf gelöscht in den Einstellungen, aber es kommen nach wie vor die Kefen am Anfang).

Viele Grüsse
Rita

**Comment by MichaelRoethlin** [comment]
Liebe Rita

Das ist schon sehr komisch ... ich habe grade mit meinem iPod mit iOS 6.1.6 getestet und bei mir gehts (du hast vermutlich gleich gelöscht):
- Einstellungen: Safari --> `Cookies und Daten löschen`
- Einstellungen: Safari --> `Cookies erlauben`: immer

![thumb_img_0002_1024](https://cloud.githubusercontent.com/assets/4992205/16801598/f5ad149e-48fb-11e6-8301-1c79571e3494.jpg)

![thumb_img_0003_1024](https://cloud.githubusercontent.com/assets/4992205/16801602/f91b330e-48fb-11e6-8912-9c456bc4eb72.jpg)

Danach gehts bei mir:

![thumb_img_0006_1024](https://cloud.githubusercontent.com/assets/4992205/16801611/0ac20cea-48fc-11e6-83b9-822df554e775.jpg)

**Comment by thomasbrunnerbfh** [comment]
das mit "käse" macht sinn. demfall würde ich es so lassen...
