### ISSUE TITLE
App-Hamburger durch Birne ersetzen? (Maruschka)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#20]
- Vorschlag: Logo oben links (Hamburger) aus Gründen der Konsequenz und Konsistenz mit angebissener Birne ersetzen.

**Comment by lucasetti** [comment]
kuule Idee!
Bin bzgl. Verständnis aber etwas skeptisch... es muss ja schon noch als Menü verstanden werden... :-)
