### ISSUE TITLE
Nutzen und Nutzung der App kurz erklären? (Maruschka)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#21]
- Was  ist Ziel und Zweck dieser App?
- Welchen Mehrwert bietet diese App mir als Benutzer?
- Warum (und für wen) lohnt sich der Aufwand, die eigene Lebensmittel-Vernichtung zu dokumentieren?

**Comment by lucasetti** [comment]
ja, könnte man sicher auch noch irgendwo in der App unterbringen! Sicher aber in den Stores, im Anschreiben und auf der Webseite! 

Inhalt @ FSM
Umsetzung @ TI
