### ISSUE TITLE
Eingabefeld Lebensmittel, Änderungsvorschlag (Maruschka)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#24]
- Alternativ-Vorschlag: Auswahl-Menü mit Oberkategorien (z.B. Gemüse, Früchte, Brotwaren, ...) bilden, bei dem man durch Verfeinerung in 3-5 Schritten beim gemeinten Lebensmittel landet.

**Comment by lucasetti** [comment]
hatten wir auch schon diskutiert und als nicht wirklich zielführend bzgl. Benutzerfreundlichkeit erachtet...
(aber es ist nie zu spät :-)
