### ISSUE TITLE
Quantifizierung streichen? (Maruschka)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#27]
Auswahlmenü "Quantifizierung(?)"
- Bug: Erklärender Text wird nicht vollständig angezeigt. Zu sehen ist nur "Quantif…".
- Wem bringt das Eintragen dieser Angabe welchen Mehrwert?
- Vorschlag: Ersatzlos streichen.

**Comment by lucasetti** [comment]
Wurde alles schon ausführlich besprochen, aber von mir aus ok.
finde nach wie vor keine anderes Wort, Mehrwert anzweifelbar > streichen! :-)
