### ISSUE TITLE
Fotografieren: englische Texte (Maruschka)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#29]
- Das Fotografieren mit der Kamera funktioniert. Die Texte werden aber stets in englischer Sprache angezeigt.

**Comment by lucasetti** [comment]
bei mir funktioniert die Funktion gar nicht. Kann nur Datei auswählen.
(Sony Xperia Z1)
funktionierte aber auch schon! :-)
Icon anpassen! werde Vorlage liefern!
@lucasetti

**Comment by lucasetti** [comment]
icon bitte ersetzen, Ersatz ist im Ordner
