### ISSUE TITLE
sharefunktion

### ISSUE THREAD

**Issue by lucasetti** [MeAndMyFood/evolution#36]
kommt da noch was?

Was ist mit rating in den Stores (von mir aus nicht so wichtig...)

**Comment by MichaelRoethlin** [comment]
Du meinst den Menüpunkt "Weiterempfehlen", gell? 

Der dort sichtbare Button "Mach mit bei MeAndMyFood" wird das Social-Media-Plugin aufrufen (in der letzten Testversion war irgend etwas falsch konfiguriert) und ein "Posten" der Webseite auf SMS, E-Mail, FB, Twitter etc. erlauben.

Also, eigentlich schon drin, aber funktionierte zuletzt nicht richtig!
