### ISSUE TITLE
Rundungen

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#38]
Durch die hinterlegten Algorithmen zur Gewichts-, Wert- und Kalorienberechnung werden zu grossen Datenmengen und zu hohe "Präzision" zum Server geschickt.

`'resultchf' => 0.344198999999999977195130895779584534466266632080078125,
 'resultkcal' => 56.10000000000000142108547152020037174224853515625,`

Vorschlag Rundungsregeln:
- Gramm, CHF und kCal werden bereits bei der Berechnung auf der App auf 2 Dezimalzahlen  gerundet und gespeichert.
- Zum Server geschickt sowie dort gespeichert wird in der gleichen Präzision.

**Comment by lucasetti** [comment]
Von mir aus tipptopp

Am 15.08.2016 3:00 nachm. schrieb "Michael Röthlin" <
notifications@github.com>:
