### ISSUE TITLE
Entsorgungswege (Thomas)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#4]
hatten wir schön öfter diskutiert: bioabfallsammlung mag man in zürich vielleicht sagen, aber an anderen orten heisst das grünabfuhr. ich fände es wichtig, wenn **beide begriffe** stehen würden (platz hat es ja genug).

**Comment by lucasetti** [comment]
ja bitte anpassen, ging wohl seit dem letzten Treffen vergessen
Im file categories_assessment_and_info_texts_05 ist es angepasst
