### ISSUE TITLE
Eigener Kompost (Thomas)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#5]
eigener kompost (würde das eigene nicht in klammern setzten, weil die grünabfuhr z.T. auch auf den kompost geht). hier soll nur ankreuzen, wer es auf seinen eigenen kompost wirft oder allenfalls noch auf den kompost des nachbarns...

**Comment by lucasetti** [comment]
einverstanden! und angepasst!
