### ISSUE TITLE
Prio 1: Erfassungsbildschirm: Erzwungene Hilfe für Carousel-Weiter

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#50]
Beim ersten Start wird erzwungen, dass ein Popup mit dem Hinweis kommt, dass es mit der Swipe-Geste nach weiter geht.a

**Comment by MichaelRoethlin** [comment]
"Wischen von rechts nach links", Bild vom Hilfetext 1. Seite ...

**Comment by pry1** [comment]
Bitte Text im Popup überprüfen!
