### ISSUE TITLE
Mindest(ens) haltbar bis (Thomas)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#6]
heisst es wirklich „mindest haltbar bis“ oder „mindestens haltbar bis“? bitte checken.

**Comment by MichaelRoethlin** [comment]
Ich würde sagen, "mindestens haltbar bis"

**Comment by lucasetti** [comment]
Migros sagt auch "mindestens" :-) Danke für den Hinweis!

**Comment by lucasetti** [comment]
in categories_assessment_and_info_texts_05 angepasst.
Bitte für neue Version übernehmen.
