### ISSUE TITLE
Entsorgungsgründe (Thomas)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#7]
bei den gründen: „kritisch/schlecht schmeckend“ und „schmeckt mir nicht“ sind nicht eindeutig formuliert. ich weiss, was ihr damit wollt und dass es sich auch unterscheidet, aber ganz klar wird das nicht. allerdings fällt mir auch nicht gerade was besseres ein.

**Comment by MichaelRoethlin** [comment]
Hmm, ist es der Unterschied zwischen riechen/schmecken?

Vorschlag: schärfer trennen, mit
- komischer Geruch
- schmeckt mir nicht

**Comment by MichaelRoethlin** [comment]
Maruschkas Vorschlag: Zusammenfassen der Möglichkeiten zu 5 Punkten: 
1. Lebensmittel sicher verdorben;
2. Lebensmittel vermutlich verdorben; 
3. Aufgedrucktes Datum verstrichen (-> evtl. Filterfrage, gefolgt von "Datum zu verbrauchen bis" oder "mindestens haltbar bis"; 
4. Überversorgung (d.h. ich habe zu viele Lebensmittel eingekauft, bin satt, habe keine Lust mehr, bin satt etc.); 
5. Das (zubereitete) Lebensmittel schmeckt mir nicht; Spontaner Entscheid, anderswo zu essen.

**Comment by lucasetti** [comment]
@ input Thomas: Ich denke mit dem "/Fehleinkauf" sollte das "schmeckt mir nicht" schon etwas klarer werden, andere Lösung sehe ich gerade auch nicht... Würde es also so belassen. Allenfalls wäre "mag ich nicht" noch eine gangbare Lösung...
@ Input Maruska: Danke für diesen Input! Wenn auch gewisse Argumente für eine Anpassung sprechen, kommt der Input meines Erachtens etwas spät... und eine Anpassung in allen Dimensionen scheint mir zum jetzigen Zeitpunkt nicht sinnvoll. Zudem haben wir die bisherigen Entsorgungsgründe schon ausführlich diskutiert.
Gleichwohl ein paar Kommentare (der Vollständigkeit halber :-)):
Sicher oder vermutlich verdorben finde ich eine spannenden Ansatz! Mit der bisherigen Lösung wollen wir das zumindest teilweise und v.a. objektiver abdecken i.S.v. z.B. riecht es "nur" komisch (=vermutlich) oder ist es schimmlig etc (=sicher).
MHD mit Filter wäre sicher auch spannend (v.a. da man die Leute allenfalls weniger sofort mit den zwei Termini konfrontiert) aber wohl technisch und vor allem auch von der Benutzerfreundlichkeit....
4. und 5. sind in meinen Augen Kategorisierungen, die auf der Analyseebene wohl sinnvoll, für die Erhebung sind mehr Details gleichwohl wünschenswert!
Die "ich habe zu viele LM eingekauft" ist übrigens mit Absicht nicht dabei, da sie analytisch etwas anders ist als alle/die meisten andren vgl. Diskussion über Gründe und Ursachen :-) Eine perfekte Lösung sehe ich hier nach wie vor nicht. Ursprünglich war die Idee, dass diese ursächlichen Einflüsse über den FB abgedeckt werden....

**Comment by thomasbrunnerbfh** [comment]
"mag ich nicht" mag ich ;-)

**Comment by lucasetti** [comment]
Text in categories_assessment_and_info_texts_05 angepasst.
Bitte für neue Version übernehmen.
