### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by ssr3** [MeAndMyFood/evolution#71]
Heute (beim Handy des Kollegen):
- wenn ich "Apfel" eingebe, kommt nur "Apfelsaft" in der Liste (komisch, aber man kann wohl trotzdem weitermachen)
- bei Einheitwahl ist die Wahlliste leer! --> So kann man die Eingabe nicht abschliessen :(

**Comment by MichaelRoethlin** [comment]
- Die Einheitenauswahl funktioniert grundsätzlich, sobald ein Lebensmittel entweder aus der Liste (bei Android muss evtl. 2x selektiert werden, je nach Version ...) oder manuell erfasst wurde
- Bei "Halbzuständen" kommt keine Auswahl
- Ein entsprechender Hinweis wurde in der App-Hilfe unter https://meandmyfood.ch/de/projekt/hilfe/ jetzt hinterlegt (Nr. 3)
