### ISSUE TITLE
Speichern/veröffentlichen (Thomas)

### ISSUE THREAD

**Issue by MichaelRoethlin** [MeAndMyFood/evolution#8]
was soll das am schluss mit veröffentlichen? speichen ist klar, aber veröffentlichen?!

**Comment by MichaelRoethlin** [comment]
Ich würde vorschlagen, wir lassen "veröffentlichen" weg.

**Comment by lucasetti** [comment]
Ja, bitte!! :-)
Das mit dem Veröffentlichen kann dann immer noch in den Disclaimer/die AGB!
